app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('log');
});

Route::resource('medico','MedicoController');
Route::resource('paciente','PacienteController');
Route::resource('admin','AdminController');

/*escalas*/
Route::resource('cincinnati','CincinnatiController');
Route::post('cincinnati/{pacienteId}', 'CincinnatiController@store');

Route::resource('neuro-canadiense','CanadienseController');
Route::post('neuro-canadiense/{pacienteId}', 'CanadienseController@store');

Route::resource('escandinava-ictus','EscandinavaIctusController');
Route::post('escandinava-ictus/{pacienteId}', 'EscandinavaIctusController@store');

Route::resource('indice-barthel','IndiceBarthelController');
Route::post('indice-barthel/{pacienteId}', 'IndiceBarthelController@store');

Route::resource('rankin','RankinController');
Route::post('rankin/{pacienteId}', 'RankinController@store');

Route::resource('hunt-hess','HuntHessController');
Route::post('hunt-hess/{pacienteId}', 'HuntHessController@store');

Route::resource('mini-mental','MiniMentalController');
Route::post('mini-mental/{pacienteId}', 'MiniMentalController@store');

Route::resource('test-mental','TestMentalController');
Route::post('test-mental/{pacienteId}', 'TestMentalController@store');

Route::resource('test-mental-abreviado','TestMentalAbreviadoController');
Route::post('test-mental-abreviado/{pacienteId}', 'TestMentalAbreviadoController@store');

Route::resource('hoehn-yahr','HoehnYahrController');
Route::post('hoehn-yahr/{pacienteId}', 'HoehnYahrController@store');

Route::resource('schwab','SchwabController');
Route::post('schwab/{pacienteId}', 'SchwabController@store');

Route::resource('hachinski','HachinskiController');
Route::post('hachinski/{pacienteId}', 'HachinskiController@store');

Route::resource('nihss','NIHSSController');
Route::post('nihss/{pacienteId}', 'NIHSSController@store');

Route::resource('valoracion-clinica','ValoracionClinicaController');
Route::post('valoracion-clinica/{pacienteId}', 'ValoracionClinicaController@store');

Route::resource('updrs','UPDRSController');
Route::post('updrs/{pacienteId}', 'UPDRSController@store');

Route::resource('valoracion-parkinson','EvaluavionParkinsonController');
Route::post('valoracion-parkinson/{pacienteId}', 'EvaluavionParkinsonController@store');


Route::get('paciente/{pacienteId}/listado', 'MedicoListadoController@index');

Route::get('graficos/{pacienteId}', 'MedicoListadoController@grafico');

Route::resource('log','LogController');
Route::get('logout','LogController@logout');

//Graficos de Escalas
Route::group(['prefix' => 'grafico'], function () {
    Route::get('mental-abreviado/{paciente_id?}', [
        'as'   => 'grafico.mental-abreviado',
        'uses' => 'GraficoEscala@mentalAbreviadoIndex'
    ]);
    Route::get('test-mental/{paciente_id?}', [
        'as'   => 'grafico.test-mental',
        'uses' => 'GraficoEscala@testMentalIndex'
    ]);

    Route::get('mini-mental/{paciente_id?}', [
        'as'   => 'grafico.mini-mental',
        'uses' => 'GraficoEscala@miniMentalIndex'
    ]);

    Route::get('barthel/{paciente_id?}', [
        'as'   => 'grafico.barthel',
        'uses' => 'GraficoEscala@barthelIndex'
    ]);

    Route::get('escandinava/{paciente_id?}', [
        'as'   => 'grafico.escandinava',
        'uses' => 'GraficoEscala@escandinavaIctusIndex'
    ]);

    Route::get('cincinnati/{paciente_id?}', [
        'as'   => 'grafico.cincinnati',
        'uses' => 'GraficoEscala@cincinnatiIndex'
    ]);

    Route::get('hunt-hess/{paciente_id?}', [
        'as'   => 'grafico.hunt-hess',
        'uses' => 'GraficoEscala@huntHessIndex'
    ]);

    Route::get('hoehn-yahr/{paciente_id?}', [
        'as'   => 'grafico.hoehn-yahr',
        'uses' => 'GraficoEscala@hoehnYahrIndex'
    ]);

    Route::get('rankin-modificado/{paciente_id?}', [
        'as'   => 'grafico.rankin-modificado',
        'uses' => 'GraficoEscala@rankinIndex'
    ]);

    Route::get('schwab/{paciente_id?}', [
        'as'   => 'grafico.schwab',
        'uses' => 'GraficoEscala@schwabIndex'
    ]);

    Route::get('hachinski/{paciente_id?}', [
        'as'   => 'grafico.hachinski',
        'uses' => 'GraficoEscala@hachinskiIndex'
    ]);

    Route::get('nihss/{paciente_id?}', [
        'as'   => 'grafico.nihss',
        'uses' => 'GraficoEscala@nihssIndex'
    ]);

    Route::get('valoracion/{paciente_id?}', [
        'as'   => 'grafico.valoracion',
        'uses' => 'GraficoEscala@valoracionClinicaIndex'
    ]);

    Route::get('canadiense/{paciente_id?}', [
        'as'   => 'grafico.canadiense',
        'uses' => 'GraficoEscala@canadienseIndex'
    ]);

    Route::get('evaluacion-parkinson/{paciente_id?}', [
        'as'   => 'grafico.evaluacion-parkinson',
        'uses' => 'GraficoEscala@evalucacionparkinsonIndex'
    ]);
    Route::get('updrs/{paciente_id?}', [
        'as'   => 'grafico.updrs',
        'uses' => 'GraficoEscala@updrsIndex'
    ]);

});

Route::get('crear-registros', function () {
    $admin= new \App\Model\Admin();
    $admin->nombre='admin_nombre';
    $admin->apellido='admin_apellido';
    $admin->email='admin@admin.com';
    $admin->password='1234';
    $admin->save();

    $medico= new \App\Model\Medico();
    $medico->nombre='medico_nombre';
    $medico->apellido='medico_apellido';
    $medico->especialidad='internista';
    $medico->email='medico@medico.com';
    $medico->password='1234';
    $medico->save();

    $paciente= new \App\Model\Paciente();
    $paciente->nombre='paciente_nombre';
    $paciente->apellido='paciente_apellido';
    $paciente->cedula='123456789';
    $paciente->direccion='paciente_direccion';
    $paciente->email='paciente@paciente.com';
    $paciente->password='1234';
    $paciente->medicos_id=1;
    $paciente->save();

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>Proyecto - Medicina</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/dt-1.10.11/datatables.min.css"/>

    <link rel="stylesheet" href={{URL::asset('css/datepicker3.css')}}>
    <link rel="stylesheet" href={{URL::asset('css/styles.css')}}>

    <script type="text/javascript" src="{{ URL::asset('js/lumino.glyphs.js') }}"></script>

    <!--[if lt IE 9]>
    <script type="text/javascript" src="{{ URL::asset('js/html5shiv.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/respond.min.js') }}"></script>
    <![endif]-->
    @yield('css')
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span><img src="{{URL::asset('img/LogoUnisinuWhite.png')}}" style="height: 60px" class="img-responsive" alt="Responsive image"></span></a>
            <ul class="user-menu">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <svg class="glyph stroked male-user">
                            <use xlink:href="#stroked-male-user"></use>
                        </svg>
                        <span class="caret"></span></a>

                    <ul class="dropdown-menu" role="menu">

                        @if (Auth::guard('web_medico')->check())

                            <li>
                                <a href="{{ route('medico.edit',Auth::guard('web_medico')->user()->id) }}">
                                    <svg class="glyph stroked male-user">
                                        <use xlink:href="#stroked-male-user"></use>
                                    </svg>
                                    Perfil
                                </a>
                            </li>

                        @elseif(Auth::guard('web_paciente')->check())
                            <li>
                                <a href="{{ route('paciente.edit',Auth::guard('web_paciente')->user()->id) }}">
                                    <svg class="glyph stroked male-user">
                                        <use xlink:href="#stroked-male-user"></use>
                                    </svg>
                                    Perfil
                                </a>
                            </li>

                        @endif
                            <li><a href="{{ url('/logout') }}">
                                <svg class="glyph stroked cancel">
                                    <use xlink:href="#stroked-cancel"></use>
                                </svg>
                                Salir</a>
                            </li>
                    </ul>
                </li>
            </ul>
        </div>

    </div><!-- /.container-fluid -->
</nav>

<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <form role="search">

    </form>
    <ul class="nav menu">

        @if (Auth::guard('web_medico')->check())
            <li class="active"><a href="{{ URL::route('medico.index') }}">
                    <svg class="glyph stroked dashboard-dial">
                        <use xlink:href="#stroked-dashboard-dial"></use>
                    </svg>
                    Dashboard</a></li>
        @elseif(Auth::guard('web_admin')->check())
            <li class="active"><a href="{{ URL::route('admin.index') }}">
                    <svg class="glyph stroked dashboard-dial">
                        <use xlink:href="#stroked-dashboard-dial"></use>
                    </svg>
                    Dashboard</a></li>
        @elseif(Auth::guard('web_paciente')->check())
            <li class="active"><a href="{{ URL::route('paciente.index') }}">
                    <svg class="glyph stroked dashboard-dial">
                        <use xlink:href="#stroked-dashboard-dial"></use>
                    </svg>
                    Dashboard</a></li>
        @endif


        @yield('opciones')


        <li role="presentation" class="divider"></li>
        <li><a href="{{ url('/logout') }}">
                <svg class="glyph stroked male-user">
                    <use xlink:href="#stroked-male-user"></use>
                </svg>
                Salir</a></li>
    </ul>

</div><!--/.sidebar-->

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <svg class="glyph stroked home">
                        <use xlink:href="#stroked-home"></use>
                    </svg>
                </a></li>
            <li class="active">Icons</li>
        </ol>
    </div><!--/.row-->

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
    </div><!--/.row-->
    @yield('includes')

    @yield('panel-tabla')



</div>    <!--/.main-->


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/t/bs/dt-1.10.11/datatables.min.js"></script>

<script type="text/javascript" src="{{ URL::asset('js/jquery.validate.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('js/messages_es.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('js/additional-methods.min.js') }}"></script>

@stack('script')
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });


    !function ($) {
        $(document).on("click", "ul.nav li.parent > a > span.icon", function () {
            $(this).find('em:first').toggleClass("glyphicon-minus");
        });
        $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
    }(window.jQuery);

    $(window).on('resize', function () {
        if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
    })
    $(window).on('resize', function () {
        if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
    })
</script>
</body>

</html>